CREATE UNIQUE INDEX IF NOT EXISTS "RXNCONSO_RXAUI_uindex" ON "RXNCONSO" ("RXAUI");

CREATE INDEX IF NOT EXISTS "X_RXNCONSO_STR" ON "RXNCONSO" ("STR");

CREATE INDEX IF NOT EXISTS "X_RXNCONSO_RXCUI" ON "RXNCONSO" ("RXCUI");

CREATE INDEX IF NOT EXISTS "X_RXNCONSO_TTY" ON "RXNCONSO" ("TTY");

CREATE INDEX IF NOT EXISTS "X_RXNCONSO_CODE" ON "RXNCONSO" ("CODE");