CREATE UNIQUE INDEX IF NOT EXISTS "RXNREL_RXAUI1_RXCUI1_RXAUI2_RXCUI2_REL_RUI_uindex" ON "RXNREL" ("RXAUI1", "RXCUI1", "RXAUI2", "RXCUI2", "REL", "RUI");

CREATE INDEX IF NOT EXISTS "X_RXNREL_RXCUI1" ON "RXNREL" ("RXCUI1");

CREATE INDEX IF NOT EXISTS "X_RXNREL_RXCUI2" ON "RXNREL" ("RXCUI2");

CREATE INDEX IF NOT EXISTS "X_RXNREL_RELA" ON "RXNREL" ("RELA");