CREATE UNIQUE INDEX IF NOT EXISTS "RXNSAT_RXAUI_RXCUI_SAB_ATN_ATV_uindex" ON "RXNSAT" ("RXAUI", "RXCUI", "SAB", "ATN", "ATV");

CREATE INDEX IF NOT EXISTS "X_RXNSAT_RXCUI" ON "RXNSAT" ("RXCUI");

CREATE INDEX IF NOT EXISTS "X_RXNSAT_ATV" ON "RXNSAT" ("ATV");

CREATE INDEX IF NOT EXISTS "X_RXNSAT_ATN" ON "RXNSAT" ("ATN");