CREATE DATABASE "RXNORM" WITH OWNER "postgres";

CREATE TABLE "RXNCONSO"
(
  "RXCUI"    VARCHAR(8)                                    NOT NULL,
  "LAT"      VARCHAR(3) DEFAULT 'ENG' :: CHARACTER VARYING NOT NULL,
  "TS"       VARCHAR(1),
  "LUI"      VARCHAR(8),
  "STT"      VARCHAR(3),
  "SUI"      VARCHAR(8),
  "ISPREF"   VARCHAR(1),
  "RXAUI"    VARCHAR(8)                                    NOT NULL,
  "SAUI"     VARCHAR(50),
  "SCUI"     VARCHAR(50),
  "SDUI"     VARCHAR(50),
  "SAB"      VARCHAR(20)                                   NOT NULL,
  "TTY"      VARCHAR(20)                                   NOT NULL,
  "CODE"     VARCHAR(50)                                   NOT NULL,
  "STR"      VARCHAR(3000)                                 NOT NULL,
  "SRL"      VARCHAR(10),
  "SUPPRESS" VARCHAR(1),
  "CVF"      VARCHAR(50),
  CONSTRAINT "RXNCONSO_pk" PRIMARY KEY ("RXAUI")
);

ALTER TABLE "RXNCONSO" OWNER TO "postgres";

CREATE UNIQUE INDEX "RXNCONSO_RXAUI_uindex" ON "RXNCONSO" ("RXAUI");

CREATE INDEX "X_RXNCONSO_STR" ON "RXNCONSO" ("STR");

CREATE INDEX "X_RXNCONSO_RXCUI" ON "RXNCONSO" ("RXCUI");

CREATE INDEX "X_RXNCONSO_TTY" ON "RXNCONSO" ("TTY");

CREATE INDEX "X_RXNCONSO_CODE" ON "RXNCONSO" ("CODE");

CREATE TABLE "RXNSAT"
(
  "RXCUI"    VARCHAR(8)    NOT NULL,
  "LUI"      VARCHAR(8),
  "SUI"      VARCHAR(8),
  "RXAUI"    VARCHAR(8)    NOT NULL,
  "STYPE"    VARCHAR(50),
  "CODE"     VARCHAR(50),
  "ATUI"     VARCHAR(11),
  "SATUI"    VARCHAR(50),
  "ATN"      VARCHAR(1000) NOT NULL,
  "SAB"      VARCHAR(20)   NOT NULL,
  "ATV"      VARCHAR(4000) NOT NULL,
  "SUPPRESS" VARCHAR(1),
  "CVF"      VARCHAR(50),
  CONSTRAINT "RXNSAT_pk" PRIMARY KEY ("RXAUI", "RXCUI", "SAB", "ATN", "ATV")
);

ALTER TABLE "RXNSAT" OWNER TO "postgres";

CREATE UNIQUE INDEX "RXNSAT_RXAUI_RXCUI_SAB_ATN_ATV_uindex" ON "RXNSAT" ("RXAUI", "RXCUI", "SAB", "ATN", "ATV");

CREATE INDEX "X_RXNSAT_RXCUI" ON "RXNSAT" ("RXCUI");

CREATE INDEX "X_RXNSAT_ATV" ON "RXNSAT" ("ATV");

CREATE INDEX "X_RXNSAT_ATN" ON "RXNSAT" ("ATN");

CREATE TABLE "RXNREL"
(
  "RXCUI1"   VARCHAR(8),
  "RXAUI1"   VARCHAR(8),
  "STYPE1"   VARCHAR(50),
  "REL"      VARCHAR(4)  NOT NULL,
  "RXCUI2"   VARCHAR(8),
  "RXAUI2"   VARCHAR(8),
  "STYPE2"   VARCHAR(50),
  "RELA"     VARCHAR(100),
  "RUI"      VARCHAR(10),
  "SRUI"     VARCHAR(50),
  "SAB"      VARCHAR(20) NOT NULL,
  "SL"       VARCHAR(1000),
  "DIR"      VARCHAR(1),
  "RG"       VARCHAR(10),
  "SUPPRESS" VARCHAR(1),
  "CVF"      VARCHAR(50)
);

ALTER TABLE "RXNREL" OWNER TO "postgres";
